### PR TITLE
data file ostia_monthly.nc is now a masked array

### PR DESCRIPTION
**Pull request by corinnebosley**
@marqh 
The data file ostia_monthly.nc contains data about ocean temperatures near the equator, and as such should be an array which is masked to oceans only, but upon discussion with my colleagues I became aware that the array was not masked and actually covered land regions as well.

The replacement file is a masked array of the data, covering ocean regions only.

### CODE REVIEW

**Comment by pelson** [comment]
Just to note, this change has resulted in the file size increasing from 1.7MB to 3.3MB.

**Comment by pelson** [comment]
Interestingly, the data type of the surface temperature has changed from float (32 bit) to double (64 bit).

**Comment by pelson** [comment]
How did you go about masking the data @corinnebosley?

**Comment by corinnebosley** [comment]
The original mask array was for land, so I inverted it (just using maths) and then multiplied it with the data cube.  I didn't use a numpy masking operation because I don't fully understand them, but if that will reduce the file size I can try that instead?

**Comment by pelson** [comment]
>  I didn't use a numpy masking operation because I don't fully understand them, but if that will reduce the file size I can try that instead? 

Yeah, that would be interesting. I may be naive about how NetCDF stores masked data, but I think it is conceivable to store 32 bit masked data.

Simply doing:

```
new_data = np.ma.masked_array(original_data, mask=the_land_mask)
```

Might do the trick here.

**Comment by corinnebosley** [comment]
I have a feeling I tried that and a few variations of it, and I only ever got a single value out of it rather than a cube, but I will see what I can do.

**Comment by ajdawson** [comment]
The variable stored in the original file was `surface_temperature`, which is valid over land. I'm guessing you know more about the product than I do and that this is somehow spurious? A masked version might be better off with a different name though, just something to think about.

**Comment by corinnebosley** [comment]
> The variable stored in the original file was surface_temperature, which is valid over land.

The code which originally generated the data appears to show it came from an SST dataset: https://github.com/SciTools/iris-sample-data/blob/master/generate_from_data_zoo.py#L25. 

Beyond the actual mask change, my new datafile has the following diff from ```ncdump -h```:

```
diff -N ostia_monthy_orig.txt ostia_monthly_new.txt
1c1
< netcdf ostia_monthly {
---
> netcdf ostia_monthly_masked {
8a9
> 		surface_temperature:_FillValue = 1.e+20f ;
11c12
< 		surface_temperature:ukmo__um_stash_source = "m01s00i024" ;
---
> 		surface_temperature:um_stash_source = "m01s00i024" ;
18,19c19
< 		latitude_longitude:semi_major_axis = 6371229. ;
< 		latitude_longitude:semi_minor_axis = 6371229. ;
---
> 		latitude_longitude:earth_radius = 6371229. ;
```

**Comment by ajdawson** [comment]
More out of curiosity than anything: if it was from SST, how did the values over land get there? I was more meaning the standard name `surface_temperature` indicates a field valid over land and sea, and would have expected the data to come from a variable named `sea_surface_temperature`. Does the OSTIA system output surface temperature over land as well?

**Comment by pelson** [comment]
> if it was from SST, how did the values over land get there? I was more meaning the standard name surface_temperature indicates a field valid over land and sea

Yeah, I was curious about that too. When you visualise it the data is moderately garbled over land, but isn't constant. It is a strange one. Looking at the OSTIA web page, looks like it is only SST: http://ghrsst-pp.metoffice.com/pages/latest_analysis/ostia.html.

**Comment by ajdawson** [comment]
That was the impression I got too, but it isn't too much of a stretch to imagine the OSTIA analysis system involves an atmospheric component I suppose... I'd be quite keen to get to the bottom of this and work out what actually is in that file!

**Comment by marqh** [comment]
I have had more feedback on this data set

the original data is sea surface temperature; it is intended to be used with a mask, but the missing data value is not correctly set in the legacy format.  

It is not clear what the meaning of the data over land points is supposed to be.

People who know more than I do suggest that having data labelled OSTIA that has land points is confusing and have suggested that our sample data should be appropriately masked

**Comment by marqh** [comment]
as the file size is now pretty much the same as previously I am minded to merge this

@pelson @ajdawson 
do you have further objections or concerns?

**Comment by ajdawson** [comment]
No concerns over the data, the provenance issues seem clear now. I suspect the existing example in iris that uses this data file will need the test image updating once this goes in, but that should be taken care of in the corresponding iris PR.

**Pull request merged**
