### PR TITLE
Add data for dask_course in Scitools courses repo

### PR DESCRIPTION
**Pull request by kaedonkers**
120 .pp files containing northward sea ice velocity needed for the dask_intro.ipynb notebook, which is part of the SciTools/courses repo (see https://github.com/SciTools/courses/pull/107).

### CODE REVIEW

**Comment by dkillick** [comment]
Looks good 👍

**Comment by pelson** [comment]
@dkillick - the dataset looks useful for the dask course, but I'm not (yet) convinced that it is necessary to exist in the sample data. We have taken great pains to keep the sample data lean, and this adds 50%  more data (from ~30MB -> 45MB). Are we able to find a way to keep sample-data slim whilst still satisfying the requirement for the course?

cc: @kaedonkers

**Comment by dkillick** [comment]
@pelson seems a bit miserly – 15MB extra really isn't much in any real terms. 

The whole point of this extra data is that we needed a lot of _files_, so we deliberately chose small files so that even 120 new files still wouldn't be particularly large (and so adhering to the intent of being lean with what we have in the sample data).

We traditionally keep files used by the courses in the sample data, and it would be nice not to break that pattern in this case. If we did we'd end up with most of the courses working one way and the dask course being completely different, which would be a bit jarring to the learner.

That said, I get your point (and considered it myself before merging this). The simple fact was there wasn't anywhere else obvious to store these, and the overall size increase wasn't dramatic in real terms. Still, if we can find somewhere else that's easily accessible to store these files instead then I'd be up for that. We could also consider compressing these files - either literally by adding them as a tarball instead, or lossily (such as decimating or truncating the files' data arrays).

**Comment by bjlittle** [comment]
It would be kinda nice if **all** the sample data was compressed, and Iris was smart enough to uncompress it on the fly, or uncompress and cache it to local disk? 

The devil is in the detail, as there will be some user permission issues for installations not owned by the user, but it's worth pausing to consider.

I can appreciate both @pelson and @dkillick points of view.

Just floating an alternative (not fully thought through, at all) option...

**Comment by bjlittle** [comment]
See https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html

It might be possible for the `iris-sample-data` conda package to uncompress the data on install with a recipe `post-link` script and then tidy up the uncompressed files on package removal with the recipe `pre-unlink` script.

Thoughts?

**Comment by pelson** [comment]
@dkillick - my concern is for the size of the git repository, not the size of the deployed files. In that context, 15MB is actually often quite painful to ```git clone```. Have you ever looked at git large file support? It seems that it may be the better option for this repository.

**Pull request merged**
