### PR TITLE
PEP440 compatible version.

### PR DESCRIPTION
**Pull request by bjlittle**
Response to [comment](https://github.com/SciTools/iris-sample-data/pull/19#issuecomment-226562710).

### CODE REVIEW

**Comment by dkillick** [comment]
This is nice, but why the move away from SemVer? If we're using SemVer elsewhere surely it makes the most sense to use SemVer here too so that we're not using multiple tools to do the same job?

**Comment by bjlittle** [comment]
I guess the bigger question is, should we move to PEP440 across the scitools organisation ?

I think we either buy in completely or not at all ...

**Comment by bjlittle** [comment]
I'm happy to park this PR and open up a discussion on iris-dev ...

**Comment by dkillick** [comment]
> should we move to PEP440 across the scitools organisation ?

In truth that is the question I'm really asking isn't it. I don't think it's something that we alone can decide upon, so maybe the Iris-dev discussion is a good way to go for now.

**Comment by bjlittle** [comment]
I agreed. Will do.

**Comment by bjlittle** [comment]
Debate it out on [iris-dev](https://groups.google.com/forum/#!topic/scitools-iris-dev/mAttuVXRT8E) if you care ...

**Comment by pp-mo** [comment]
if you dare ...

**Pull request closed without merging**
